name: Local Heredoc Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-heredoc:
    runs-on: ubuntu-latest
    steps:
      - name: Run heredoc test locally
        shell: bash
        run: |
          echo "Starting heredoc test..."

          # Simulate getting a password or token
          TOKEN="test_token"

          # Use heredoc with <<-EOF and tabs (not spaces) for indentation stripping
          cat <<-EOF > output.txt
          	This is a test file.
          	Token is: $TOKEN
          EOF

          echo "Contents of output.txt:"
          cat output.txt

          echo "Heredoc test complete!"
